# -*- mode: python; coding: utf-8 -*-
# PyInstaller spec - pack backend/app into single-file python-backend.exe
# 使用环境变量 SUXING_REPO_ROOT 注入路径，绕过 SPECPATH 在 cp1252 下的中文截断

from pathlib import Path
import os

REPO_ROOT = Path(os.environ["SUXING_REPO_ROOT"])
BACKEND_DIR = REPO_ROOT / "backend"
ENTRY = BACKEND_DIR / "run_server.py"

PATHEX = [str(BACKEND_DIR)]

a = Analysis(
    [str(ENTRY)],
    pathex=PATHEX,
    binaries=[],
    datas=[],
    hiddenimports=[
        "app",
        "app.__init__",
        "app.main",
        "app.config",
        "app.db",
        "app.events",
        "app.indexer",
        "app.models",
        "app.parser",
        "app.repository",
        "app.providers",
        "app.thumbnails",
        "app.routes",
        "app.routes.__init__",
        "app.routes.images",
        "app.routes.folders",
        "app.routes.settings",
        "app.routes.tags",
        "app.routes.reverse_prompts",
        "app.reverse_prompts",
        "httpx",
        "httpcore",
        "certifi",
        "app.routes.comfyui",
        "app.integrations",
        "app.integrations.__init__",
        "app.integrations.comfyui",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "uvicorn.lifespan.off",
        "watchdog.observers",
        "watchdog.observers.inotify_buffer",
        "watchdog.observers.inotify_c",
        "watchdog.observers.fsevents",
        "watchdog.observers.kqueue",
        "watchdog.observers.polling",
        "watchdog.observers.read_directory_changes",
        "watchdog.observers.winapi",
        "watchdog.events",
        "PIL._imaging",
        "PIL._imagingtk",
        "PIL._imagingft",
        "PIL._imagingmath",
        "PIL._imagingmorph",
        "PIL._imagingcms",
        "PIL._imagingcms_ctypes",
        "PIL._imaginggl",
        "PIL._imagingwidgets",
        "PIL._webp",
        "PIL._avif",
        "PIL._jpeg",
        "PIL._png",
        "PIL._tkinter",
        "multipart",
        "multipart.multipart",
        "pydantic._internal._generate_schema",
        "pydantic.deprecated.decorator",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy.tests",
        "pandas",
        "scipy",
        "IPython",
        "jupyter",
        "notebook",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="python-backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,   # 保留 stdout pipe 让 Rust 检测 READY；窗口隐藏由 Rust 用 CREATE_NO_WINDOW 实现
    disable_windowed_redirect=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
